services:
  - type: web
    name: intel-brief-app
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///app.db"
      - key: ENABLE_AI_AGENTS
        value: "true"
      - key: LOG_TO_FILE
        value: "false"
      - key: RATE_LIMIT_ENABLED
        value: "true"
      - key: HEALTH_CHECK_ENABLED
        value: "true"
      - key: METRICS_ENABLED
        value: "true"