services:
  - type: web
    name: intel-brief-app
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: intel-brief-db
          property: connectionString
      - key: ENABLE_AI_AGENTS
        value: true
      - key: LOG_TO_FILE
        value: false
      - key: RATE_LIMIT_ENABLED
        value: true
      - key: HEALTH_CHECK_ENABLED
        value: true
      - key: METRICS_ENABLED
        value: true

  - type: pserv
    name: intel-brief-db
    env: postgres
    plan: starter
    databaseName: intel_brief_db
    databaseUser: intel_brief